#!/bin/sh

WHAT=https://svnhost.cs.uleth.ca/SMBC
WHERE="$HOME/Project/testdir"
FNAME=$(date +%y%m%d)

ulimit -t 10

if [ $# -eq 2 ]
then
   WHERE="$1"
   WHAT="$2"
elif [ $# -eq 1 ]
then
   WHERE="$1"
fi

cd "$WHERE"
svn update

if [ $? -eq 0 ] 
then
   make clean-all
   make -k > "./tests/$FNAME.comp.$$" 2>&1
   if [ $? -eq 0 ]
   then
      ./tester > "./tests/$FNAME.res.$$"
      svn add "./tests/$FNAME.comp.$$"
      svn add "./tests/$FNAME.res.$$"
      svn commit -m "Added the test results for today."
   else
       svn add "./tests/$FNAME.comp.$$"
       svn commit -m "Added compilation results for today; did not succeed."
   fi
   cd -
fi
